---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Install redis packages
  ansible.builtin.package:
    name: "{{ redis_packages }}"
    state: present

- name: Create basic configuration file from exmaple
  ansible.builtin.copy:
    src: /etc/redis/default.conf.example
    dest: "{{ redis_conf }}"
    mode: "0644"
    remote_src: true
    force: false
  when: ansible_os_family == 'Suse'

- name: Enable redis services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
  notify: Restart redis
  loop: "{{ redis_services }}"

- name: Merge default + overwrite settings
  ansible.builtin.set_fact:
    redis_settings: "{{ redis_settings_overwrite | combine(redis_settings_overwrite, recursive=True) }}"
  when: redis_settings_overwrite is defined

- name: Configure redis
  ansible.builtin.lineinfile:
    path: "{{ redis_conf }}"
    regexp: "(# )?{{ item.key }} .*"
    line: "{{ item.key }} {{ item.value if item.value is string else item.value | join(', ') }}"
  notify: Restart redis
  loop: "{{ redis_settings | dict2items }}"
